# pylint: skip-file
"""
user migration

Revision ID: eff79fd5d0e7
Revises: 27538a89fd3e
Create Date: 2025-07-18 14:36:54.951476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff79fd5d0e7'
down_revision = '27538a89fd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
