# pylint: skip-file
"""
kulyebyaka

Revision ID: 18ef542b418b
Revises: 2097ae464b74
Create Date: 2025-09-19 16:00:20.489010

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18ef542b418b'
down_revision = '2097ae464b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'instrument_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instruments',
        sa.Column(
            'instrument_status',
            postgresql.ENUM(
                'DRAFT',
                'PENDING_APPROVAL',
                'ACTIVE',
                'MATURED',
                name='instrument_status',
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
