# pylint: skip-file
"""
added new instrument status

Revision ID: 2097ae464b74
Revises: 78ac0799d719
Create Date: 2025-09-19 15:16:23.883151

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2097ae464b74'
down_revision = '78ac0799d719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
