# pylint: skip-file
"""
mapped instead of columns

Revision ID: 27538a89fd3e
Revises: ecf09ab8a046
Create Date: 2025-07-16 14:11:16.644096

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '27538a89fd3e'
down_revision = 'ecf09ab8a046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
