# pylint: skip-file
"""
document and document version tables

Revision ID: 2e56faa944e3
Revises: 3956243f4db8
Create Date: 2025-08-22 10:28:17.665308

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e56faa944e3'
down_revision = '3956243f4db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'documents',
        sa.Column('internal_filename', sa.String(length=255), nullable=False),
        sa.Column('mime', sa.String(length=64), nullable=False),
        sa.Column('storage_bucket', sa.String(length=100), nullable=False),
        sa.Column('storage_object_key', sa.String(length=255), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('internal_filename'),
        sa.UniqueConstraint('storage_object_key'),
    )
    op.create_index(
        op.f('ix_documents_created_at'),
        'documents',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_documents_deleted_at'),
        'documents',
        ['deleted_at'],
        unique=False,
    )
    op.create_table(
        'document_versions',
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('storage_version_id', sa.String(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.CheckConstraint(
            'version_number > 0', name='ck_version_number_positive'
        ),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['document_id'],
            ['documents.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_document_versions_created_at'),
        'document_versions',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_document_versions_deleted_at'),
        'document_versions',
        ['deleted_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_document_versions_deleted_at'), table_name='document_versions'
    )
    op.drop_index(
        op.f('ix_document_versions_created_at'), table_name='document_versions'
    )
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
