# pylint: skip-file
"""
document and document version tables


Revision ID: 3956243f4db8
Revises: 9bdf402b2dd8
Create Date: 2025-08-22 10:26:22.792321

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3956243f4db8'
down_revision = '9bdf402b2dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
