# pylint: skip-file
"""
added company addresses table

Revision ID: 44665e068177
Revises: 6eadcb39665a
Create Date: 2025-07-28 15:17:57.721897

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '44665e068177'
down_revision = '6eadcb39665a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'company_addresses',
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'REGISTERED',
                'BILLING',
                'OFFICE',
                'SHIPPING',
                'OTHER',
                name='addresstype',
            ),
            nullable=False,
        ),
        sa.Column('street', sa.String(length=255), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=False),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=False),
        sa.Column('country', sa.String(length=2), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['company_id'], ['companies.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_company_addresses_created_at'),
        'company_addresses',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_company_addresses_deleted_at'),
        'company_addresses',
        ['deleted_at'],
        unique=False,
    )
    op.drop_column('companies', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'companies',
        sa.Column(
            'country', sa.VARCHAR(length=2), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(
        op.f('ix_company_addresses_deleted_at'), table_name='company_addresses'
    )
    op.drop_index(
        op.f('ix_company_addresses_created_at'), table_name='company_addresses'
    )
    op.drop_table('company_addresses')
    # ### end Alembic commands ###
