# pylint: skip-file
"""
user migration

Revision ID: 45c13bc63341
Revises: eff79fd5d0e7
Create Date: 2025-07-18 14:41:53.662912

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '45c13bc63341'
down_revision = 'eff79fd5d0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_index(
        op.f('ix_users_created_at'), 'users', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
