# pylint: skip-file
"""
added debt instrument enitty

Revision ID: 591c3073c898
Revises: 9b47f663fc2a
Create Date: 2025-07-31 15:21:25.117457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591c3073c898'
down_revision = '9b47f663fc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
