# pylint: skip-file
"""
added a one-to-many connection between users and copmanies

Revision ID: 6eadcb39665a
Revises: 7b635e714510
Create Date: 2025-07-27 15:11:16.187743

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6eadcb39665a'
down_revision = '7b635e714510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###
