# pylint: skip-file
"""
added constraints to the document_versions

Revision ID: 78ac0799d719
Revises: 2e56faa944e3
Create Date: 2025-08-24 10:27:37.118966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ac0799d719'
down_revision = '2e56faa944e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_versions_doc_storage_ver', 'document_versions', ['document_id', 'storage_version_id'])
    op.create_unique_constraint('uq_document_versions_doc_ver', 'document_versions', ['document_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_versions_doc_ver', 'document_versions', type_='unique')
    op.drop_constraint('uq_document_versions_doc_storage_ver', 'document_versions', type_='unique')
    # ### end Alembic commands ###
