# pylint: skip-file
"""
added simple company entity

Revision ID: 7b635e714510
Revises: 45c13bc63341
Create Date: 2025-07-27 14:49:25.094423

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7b635e714510'
down_revision = '45c13bc63341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'companies',
        sa.Column('legal_name', sa.String(length=255), nullable=False),
        sa.Column('trade_name', sa.String(length=255), nullable=True),
        sa.Column('country', sa.String(length=2), nullable=False),
        sa.Column('registration_number', sa.String(length=64), nullable=False),
        sa.Column('incorporation_date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('legal_name'),
        sa.UniqueConstraint('registration_number'),
    )
    op.create_index(
        op.f('ix_companies_created_at'),
        'companies',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_companies_deleted_at'),
        'companies',
        ['deleted_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_deleted_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
