# pylint: skip-file
"""
update to the instrument types by hanc

Revision ID: 86008810d25f
Revises: 8953249a3c34
Create Date: 2025-09-19 16:17:25.532674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86008810d25f'
down_revision = '8953249a3c34'
branch_labels = None
depends_on = None

NEW = "REJECTED"  # <-- put the exact new enum label here

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE instrument_status ADD VALUE IF NOT EXISTS '{NEW}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
