# pylint: skip-file
"""
update to the instrument types

Revision ID: 8953249a3c34
Revises: 18ef542b418b
Create Date: 2025-09-19 16:00:59.752571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8953249a3c34'
down_revision = '18ef542b418b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('instrument_status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'MATURED', 'REJECTED', name='instrument_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'instrument_status')
    # ### end Alembic commands ###
