# pylint: skip-file
"""
added a new field to instrument entity - trading status

Revision ID: 991a19916552
Revises: c7e262c123f6
Create Date: 2025-11-15 16:35:46.442629

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '991a19916552'
down_revision = 'c7e262c123f6'
branch_labels = None
depends_on = None

TRADING_STATUS_ENUM = postgresql.ENUM(
    "OFF_MARKET",
    "DRAFT",
    "LISTED",
    "PAUSED",
    "UNDER_OFFER",
    "RESERVED",
    "ESCROW",
    "SETTLEMENT_PENDING",
    "CANCELLED",
    "EXPIRED",
    "SUSPENDED",
    "FAILED_SETTLEMENT",
    name="trading_status",
    # schema="public",  # uncomment if you use schemas explicitly
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    TRADING_STATUS_ENUM.create(bind, checkfirst=True)
    op.add_column(
        "instruments",
        sa.Column(
            "trading_status",
            TRADING_STATUS_ENUM,
            nullable=False,
            server_default="OFF_MARKET",  # set a default to backfill existing rows
        ),
    )
    # op.add_column('instruments', sa.Column('trading_status', sa.Enum('OFF_MARKET', 'DRAFT', 'LISTED', 'PAUSED', 'UNDER_OFFER', 'RESERVED', 'ESCROW', 'SETTLEMENT_PENDING', 'CANCELLED', 'EXPIRED', 'SUSPENDED', 'FAILED_SETTLEMENT', name='trading_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_column('instruments', 'trading_status')
    TRADING_STATUS_ENUM.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
