# pylint: skip-file
"""
added user.role field

Revision ID: 9b47f663fc2a
Revises: 44665e068177
Create Date: 2025-07-29 13:12:05.733977

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9b47f663fc2a'
down_revision = '44665e068177'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
                CREATE TYPE userrole AS ENUM ('ADMIN', 'BUYER', 'SELLER', 'ISSUER');
            END IF;
        END$$;
    """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'BUYER', 'SELLER', 'ISSUER', name='userrole'),
            server_default=sa.text("'BUYER'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
