# pylint: skip-file
"""
added debt instrument enitty

Revision ID: 9bdf402b2dd8
Revises: 591c3073c898
Create Date: 2025-07-31 15:23:18.662529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdf402b2dd8'
down_revision = '591c3073c898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('face_value', sa.Double(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('maturity_payment', sa.Double(), nullable=False),
    sa.Column('instrument_status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'MATURED', name='instrument_status'), nullable=False),
    sa.Column('maturity_status', sa.Enum('NOT_TRADING', 'PENDING', 'SETTLED', 'DEFAULTED', name='maturity_status'), nullable=False),
    sa.Column('issuer_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_created_at'), 'instruments', ['created_at'], unique=False)
    op.create_index(op.f('ix_instruments_deleted_at'), 'instruments', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_deleted_at'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_created_at'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
