# pylint: skip-file
"""
added a new instrument status SUSPENDED

Revision ID: a13ab065a013
Revises: 86008810d25f
Create Date: 2025-11-14 21:37:19.621531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a13ab065a013'
down_revision = '86008810d25f'
branch_labels = None
depends_on = None

NEW = 'SUSPENDED'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # FIXME: I am not sure wether this change did in fact happen
    op.execute(f"ALTER TYPE instrument_status ADD VALUE IF NOT EXISTS '{NEW}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
