# pylint: skip-file
"""
added instrument_ownerships table

Revision ID: a1b2c3d4e5f6
Revises: bb5ab338ea7d
Create Date: 2025-12-26 14:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'bb5ab338ea7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the acquisition_reason enum type if it doesn't exist
    acquisition_reason_enum = postgresql.ENUM(
        'ISSUANCE', 'TRADE', 'ASSIGNMENT',
        name='acquisition_reason',
        create_type=False,
    )
    acquisition_reason_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'instrument_ownerships',
        sa.Column('instrument_id', sa.UUID(), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('relinquished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'acquisition_reason',
            postgresql.ENUM('ISSUANCE', 'TRADE', 'ASSIGNMENT', name='acquisition_reason', create_type=False),
            nullable=False,
            server_default='ISSUANCE',
        ),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['instrument_id'], ['instruments.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['owner_id'], ['companies.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_instrument_ownerships_created_at'),
        'instrument_ownerships',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_instrument_ownerships_deleted_at'),
        'instrument_ownerships',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_instrument_ownerships_instrument_id'),
        'instrument_ownerships',
        ['instrument_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_instrument_ownerships_owner_id'),
        'instrument_ownerships',
        ['owner_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_instrument_ownerships_owner_id'),
        table_name='instrument_ownerships',
    )
    op.drop_index(
        op.f('ix_instrument_ownerships_instrument_id'),
        table_name='instrument_ownerships',
    )
    op.drop_index(
        op.f('ix_instrument_ownerships_deleted_at'),
        table_name='instrument_ownerships',
    )
    op.drop_index(
        op.f('ix_instrument_ownerships_created_at'),
        table_name='instrument_ownerships',
    )
    op.drop_table('instrument_ownerships')

    # Drop the enum type
    sa.Enum(name='acquisition_reason').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
