# pylint: skip-file
"""
added listings table

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-12-26 15:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the listing_status enum type if it doesn't exist
    listing_status_enum = postgresql.ENUM(
        'OPEN', 'WITHDRAWN', 'SUSPENDED',
        name='listing_status',
        create_type=False,
    )
    listing_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'listings',
        sa.Column('instrument_id', sa.UUID(), nullable=False),
        sa.Column('seller_company_id', sa.UUID(), nullable=False),
        sa.Column('listing_creator_user_id', sa.UUID(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM('OPEN', 'WITHDRAWN', 'SUSPENDED', name='listing_status', create_type=False),
            nullable=False,
            server_default='OPEN',
        ),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['instrument_id'], ['instruments.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['seller_company_id'], ['companies.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['listing_creator_user_id'], ['users.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_listings_created_at'),
        'listings',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_listings_deleted_at'),
        'listings',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_listings_instrument_id'),
        'listings',
        ['instrument_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_listings_seller_company_id'),
        'listings',
        ['seller_company_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_listings_status'),
        'listings',
        ['status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_listings_status'),
        table_name='listings',
    )
    op.drop_index(
        op.f('ix_listings_seller_company_id'),
        table_name='listings',
    )
    op.drop_index(
        op.f('ix_listings_instrument_id'),
        table_name='listings',
    )
    op.drop_index(
        op.f('ix_listings_deleted_at'),
        table_name='listings',
    )
    op.drop_index(
        op.f('ix_listings_created_at'),
        table_name='listings',
    )
    op.drop_table('listings')

    # Drop the enum type
    postgresql.ENUM(name='listing_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
