# pylint: skip-file
"""
added instrument_documents association table

Revision ID: bb5ab338ea7d
Revises: c5a7992aac0d
Create Date: 2025-12-26 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bb5ab338ea7d'
down_revision = 'c5a7992aac0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'instrument_documents',
        sa.Column('instrument_id', sa.UUID(), nullable=False),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['instrument_id'], ['instruments.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['document_id'], ['documents.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_instrument_documents_created_at'),
        'instrument_documents',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_instrument_documents_deleted_at'),
        'instrument_documents',
        ['deleted_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_instrument_documents_deleted_at'),
        table_name='instrument_documents',
    )
    op.drop_index(
        op.f('ix_instrument_documents_created_at'),
        table_name='instrument_documents',
    )
    op.drop_table('instrument_documents')
    # ### end Alembic commands ###
