# pylint: skip-file
"""
added CLOSED status to listing_status enum

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2025-12-27 12:00:00.000000

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c3d4e5f6a7b8'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None

NEW_VALUE = 'CLOSED'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"ALTER TYPE listing_status ADD VALUE IF NOT EXISTS '{NEW_VALUE}'"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL does not support removing enum values directly
    # This would require recreating the enum type and migrating data
    pass
    # ### end Alembic commands ###
