# pylint: skip-file
"""
added a new table instrument_public_payloads which sotres JSON non-uniform representation of instruments

Revision ID: c5a7992aac0d
Revises: f27b5b543a11
Create Date: 2025-11-24 15:08:51.144949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5a7992aac0d'
down_revision = 'f27b5b543a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_public_payloads',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_index(op.f('ix_instrument_public_payloads_created_at'), 'instrument_public_payloads', ['created_at'], unique=False)
    op.create_index(op.f('ix_instrument_public_payloads_deleted_at'), 'instrument_public_payloads', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_public_payloads_deleted_at'), table_name='instrument_public_payloads')
    op.drop_index(op.f('ix_instrument_public_payloads_created_at'), table_name='instrument_public_payloads')
    op.drop_table('instrument_public_payloads')
    # ### end Alembic commands ###
