# pylint: skip-file
"""
added bids table

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2025-12-27 14:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4e5f6a7b8c9'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the bid_status enum type if it doesn't exist
    bid_status_enum = postgresql.ENUM(
        'PENDING', 'WITHDRAWN', 'SUSPENDED', 'SELECTED', 'NOT_SELECTED',
        name='bid_status',
        create_type=False,
    )
    bid_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'bids',
        sa.Column('listing_id', sa.UUID(), nullable=False),
        sa.Column('bidder_company_id', sa.UUID(), nullable=False),
        sa.Column('bidder_user_id', sa.UUID(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'status',
            postgresql.ENUM(
                'PENDING', 'WITHDRAWN', 'SUSPENDED', 'SELECTED', 'NOT_SELECTED',
                name='bid_status',
                create_type=False,
            ),
            nullable=False,
            server_default='PENDING',
        ),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['listing_id'], ['listings.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['bidder_company_id'], ['companies.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['bidder_user_id'], ['users.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_bids_created_at'),
        'bids',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_bids_deleted_at'),
        'bids',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_bids_listing_id'),
        'bids',
        ['listing_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_bids_bidder_company_id'),
        'bids',
        ['bidder_company_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_bids_status'),
        'bids',
        ['status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_bids_status'),
        table_name='bids',
    )
    op.drop_index(
        op.f('ix_bids_bidder_company_id'),
        table_name='bids',
    )
    op.drop_index(
        op.f('ix_bids_listing_id'),
        table_name='bids',
    )
    op.drop_index(
        op.f('ix_bids_deleted_at'),
        table_name='bids',
    )
    op.drop_index(
        op.f('ix_bids_created_at'),
        table_name='bids',
    )
    op.drop_table('bids')

    # Drop the enum type
    postgresql.ENUM(name='bid_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
