# pylint: skip-file
"""
added asks table

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2025-12-27 16:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5f6a7b8c9d0'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ask_status enum type if it doesn't exist
    ask_status_enum = postgresql.ENUM(
        'ACTIVE',
        'WITHDRAWN',
        'SUSPENDED',
        name='ask_status',
        create_type=False,
    )
    ask_status_enum.create(op.get_bind(), checkfirst=True)

    # Create the execution_mode enum type if it doesn't exist
    execution_mode_enum = postgresql.ENUM(
        'AUTO',
        'MANUAL',
        name='execution_mode',
        create_type=False,
    )
    execution_mode_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'asks',
        sa.Column('listing_id', sa.UUID(), nullable=False),
        sa.Column('asker_company_id', sa.UUID(), nullable=False),
        sa.Column('asker_user_id', sa.UUID(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'execution_mode',
            postgresql.ENUM(
                'AUTO',
                'MANUAL',
                name='execution_mode',
                create_type=False,
            ),
            nullable=False,
            server_default='MANUAL',
        ),
        sa.Column(
            'binding', sa.Boolean(), nullable=False, server_default='false'
        ),
        sa.Column(
            'status',
            postgresql.ENUM(
                'ACTIVE',
                'WITHDRAWN',
                'SUSPENDED',
                name='ask_status',
                create_type=False,
            ),
            nullable=False,
            server_default='ACTIVE',
        ),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['listing_id'], ['listings.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['asker_company_id'], ['companies.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['asker_user_id'], ['users.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_asks_created_at'),
        'asks',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_asks_deleted_at'),
        'asks',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_asks_listing_id'),
        'asks',
        ['listing_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_asks_asker_company_id'),
        'asks',
        ['asker_company_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_asks_status'),
        'asks',
        ['status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_asks_status'),
        table_name='asks',
    )
    op.drop_index(
        op.f('ix_asks_asker_company_id'),
        table_name='asks',
    )
    op.drop_index(
        op.f('ix_asks_listing_id'),
        table_name='asks',
    )
    op.drop_index(
        op.f('ix_asks_deleted_at'),
        table_name='asks',
    )
    op.drop_index(
        op.f('ix_asks_created_at'),
        table_name='asks',
    )
    op.drop_table('asks')

    # Drop the enum types
    postgresql.ENUM(name='ask_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='execution_mode').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
