# pylint: skip-file
"""
user - added new column to track the account status

Revision ID: f27b5b543a11
Revises: 991a19916552
Create Date: 2025-11-16 21:26:35.396587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f27b5b543a11'
down_revision = '991a19916552'
branch_labels = None
depends_on = None


ACCOUNT_STATUS_ENUM = postgresql.ENUM(
    'ACTIVE',
    'INACTIVE',
    'PENDING',
    'SUSPENDED',
    'DISABLED',
    'DELETED',
    'BANNED',
    'LOCKED',
    'AWAITING_APPROVAL',
    'REJECTED',
    'ARCHIVED',
    'UNVERIFIED',
    name='account_status'
    # schema="public",  # uncomment if you use schemas explicitly
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    ACCOUNT_STATUS_ENUM.create(bind, checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "account_status",
            ACCOUNT_STATUS_ENUM,
            nullable=False,
            server_default="AWAITING_APPROVAL",  # set a default to backfill existing rows
        ),
    )
    # op.add_column('users', sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED', 'DISABLED', 'DELETED', 'BANNED', 'LOCKED', 'AWAITING_APPROVAL', 'REJECTED', 'ARCHIVED', 'UNVERIFIED', name='account_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_column('users', 'account_status')
    ACCOUNT_STATUS_ENUM.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
